version: '3.9'
services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - keploy-network

  node-app:
    build:
      context: .
    container_name: jwtSqlApp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keploy-network  

networks:
  keploy-network:
    external: true
